[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
auto_detect_solc = false
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@1inch/=lib/1inch-contracts/contracts/",
]
fs_permissions = [
    { access = "read-write", path = "broadcast" },
    { access = "read-write", path = "cache" },
    { access = "read-write", path = "out" },
]

optimizer = true
optimizer_runs = 200

[profile.default.model_checker]
contracts = { "src/DurationToken.sol" = ["DurationToken"], "src/DurationOptions.sol" = ["DurationOptions"] }

[rpc_endpoints]
base = "${BASE_RPC_URL}"
base_sepolia = "${BASE_TESTNET_RPC_URL}"
mainnet = "https://eth.llamarpc.com"
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
base_sepolia = { key = "${BASESCAN_API_KEY}" }
